# Generated by Django 5.0.1 on 2024-01-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatboot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='respons',
            new_name='response',
        ),
    ]
